"""
Trace analyzer plugin — combines uniformity analysis with trace aggregation.

Reads tasks/spans from state (after span_to_task) or loads pre-existing debug_data
files from filesystem. Groups tasks by agent node, embeds outputs with
sentence-transformers, clusters to find behavioral patterns, joins with
ground-truth labels, LLM-summarizes traces, and aggregates by run_id.

Labeling modes (checked in order):
1. labels_csv config → explicit CSV path
2. {session_dir}/cluster_labels.csv → auto-generated by .bob command
3. Interactive CLI → _user_input_fn callback (click.prompt)
4. No labels → save "cluster_info" artifacts for .bob command, return needs_labeling

Ported from:
- agentops/node_uniformity_plugin.py (Stage 1: uniformity analysis)
- agentops/experiment_pipeline.py lines 280-430 (Stage 2: trace aggregation)
"""

import asyncio
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

import polars as pl

from analytics.base_plugin import AnalyticsPlugin
from .prompt import (
    SUMMARIZE_SYSTEM_PROMPT,
    SUMMARIZE_USER_TEMPLATE,
    CLUSTER_SUMMARY_SYSTEM_PROMPT,
    CLUSTER_SUMMARY_USER_TEMPLATE,
)


class TraceAnalyzerPlugin(AnalyticsPlugin):

    def __init__(self):
        self.labels_csv = ""
        self.data_dir = ""
        self.logs_dir = ""
        self.embedding_model = "sentence-transformers/nli-distilroberta-base-v2"
        self.distance_threshold = 0.3
        self.numbers_are_meaningful = False
        self.max_concurrent_summarize = 20

    @property
    def name(self) -> str:
        return "trace_analyzer"

    @property
    def description(self) -> str:
        return (
            "Analyzes agent traces: groups by node, clusters outputs for uniformity, "
            "joins with labels, LLM-summarizes, and aggregates by run_id"
        )

    def configure(self, config: Dict[str, Any]):
        self.labels_csv = config.get("labels_csv", self.labels_csv)
        self.data_dir = config.get("data_dir", self.data_dir)
        self.logs_dir = config.get("logs_dir", self.logs_dir)
        self.embedding_model = config.get("embedding_model", self.embedding_model)
        self.distance_threshold = config.get("distance_threshold", self.distance_threshold)
        self.numbers_are_meaningful = config.get("numbers_are_meaningful", self.numbers_are_meaningful)
        self.max_concurrent_summarize = config.get(
            "max_concurrent_summarize", self.max_concurrent_summarize
        )

    async def execute(self, state: "ApplicationState") -> Dict[str, Any]:
        # Register artifact kinds for experiment pipeline
        from .models import ExperimentArtifact
        state._data_manager.register_artifact_kind("node_traces", ExperimentArtifact)
        state._data_manager.register_artifact_kind("cluster_info", ExperimentArtifact)

        # Try to load node data from state (tasks after span_to_task), otherwise from files
        node_data_list = await self._load_node_data(state)
        if not node_data_list:
            return {
                "status": "skipped",
                "message": "No node data found (no tasks in state and no debug_data files)",
                "artifacts_produced": 0,
            }

        # Resolve labels: config CSV → session-dir CSV → interactive → none
        labels_df = self._resolve_labels(state)

        from utils.llm_service import get_llm_service

        llm = get_llm_service()

        if labels_df is not None:
            # Path A: Have labels (CSV or auto-generated) → full pipeline
            self._log("Using labels from CSV.")
            return await self._run_with_labels(state, node_data_list, labels_df, llm)
        else:
            # Path B: No labels → save cluster_info for chat-agent labeling
            # The chat agent (/disambiguate command) reads cluster_info,
            # presents clusters to the user, and generates cluster_labels.csv.
            self._log("No labels — saving cluster_info for chat-agent labeling.")
            return await self._save_cluster_info(state, node_data_list, llm)

    # ── Labeling Resolution ──────────────────────────────────────

    def _resolve_labels(self, state) -> Optional[pl.DataFrame]:
        """Try loading labels from config CSV or session-dir auto-generated CSV."""
        # Priority 1: Explicit labels_csv config
        if self.labels_csv:
            df = self._load_labels_csv(self.labels_csv)
            if df is not None and not df.is_empty():
                return df
            self._log("labels_csv provided but could not load.", level="warning")

        # Priority 2: Auto-generated cluster_labels.csv in session dir
        if hasattr(state, "output_dir") and state.output_dir:
            auto_csv = Path(state.output_dir) / "cluster_labels.csv"
            if auto_csv.exists():
                self._log(f"Found auto-generated labels at {auto_csv}")
                df = self._load_labels_csv(str(auto_csv))
                if df is not None and not df.is_empty():
                    return df

        return None

    # ── Path A: Full pipeline with labels ────────────────────────

    async def _run_with_labels(
        self, state, node_data_list: List[Dict], labels_df: pl.DataFrame, llm
    ) -> Dict[str, Any]:
        """Run full pipeline: join with labels, summarize, aggregate."""

        async def _process_one(node_data):
            node_name = node_data["node_name"]
            source_data = node_data["source_data"]

            self._log(f"Processing node: {node_name} ({len(source_data)} traces)")

            df = pl.DataFrame(source_data)
            if df.is_empty():
                return None

            df = df.with_columns(pl.col("run_id").cast(pl.Utf8))
            df_labeled = df.join(labels_df, on="run_id", how="inner")

            return await self._process_labeled_node(
                state, node_name, source_data, node_data, df_labeled, llm
            )

        # Process all nodes in parallel — LLM summarization calls overlap
        results = await asyncio.gather(
            *[_process_one(nd) for nd in node_data_list],
            return_exceptions=True,
        )

        artifacts_produced = sum(
            1 for r in results if r is not None and not isinstance(r, Exception)
        )

        for i, r in enumerate(results):
            if isinstance(r, Exception):
                node_name = node_data_list[i].get("node_name", "unknown")
                self._log(f"Error processing {node_name}: {r}", level="error")

        return {
            "status": "success" if artifacts_produced > 0 else "skipped",
            "artifacts_produced": artifacts_produced,
            "nodes_processed": artifacts_produced,
        }

    # ── Path B: Interactive CLI labeling ─────────────────────────

    async def _run_interactive(
        self, state, node_data_list: List[Dict], llm
    ) -> Dict[str, Any]:
        """Run with interactive cluster labeling via _user_input_fn callback."""
        artifacts_produced = 0

        for node_data in node_data_list:
            node_name = node_data["node_name"]
            source_data = node_data["source_data"]

            self._log(f"Processing node: {node_name} ({len(source_data)} traces)")

            df = pl.DataFrame(source_data)
            if df.is_empty():
                continue
            df = df.with_columns(pl.col("run_id").cast(pl.Utf8))

            # Get interactive labels from cluster assignments
            df_labeled = await self._label_via_interactive(df, source_data, node_name, state, llm)
            if df_labeled is None:
                continue

            artifact = await self._process_labeled_node(
                state, node_name, source_data, node_data, df_labeled, llm
            )
            if artifact:
                artifacts_produced += 1

        return {
            "status": "success" if artifacts_produced > 0 else "skipped",
            "artifacts_produced": artifacts_produced,
            "nodes_processed": artifacts_produced,
        }

    # ── Path C: Save cluster_info for .bob command ───────────────

    async def _save_cluster_info(
        self, state, node_data_list: List[Dict], llm
    ) -> Dict[str, Any]:
        """Save cluster summaries as artifacts for the .bob chat-agent to present to user."""

        async def _process_one_cluster(node_data):
            node_name = node_data["node_name"]
            source_data = node_data["source_data"]

            # Check we have multiple clusters
            cluster_labels = set(d.get("cluster_label", 0) for d in source_data)
            if len(cluster_labels) < 2:
                self._log(f"Only {len(cluster_labels)} cluster(s) for {node_name}, skipping.", level="warning")
                return None

            # Group trace texts by cluster
            cluster_texts: Dict[int, List[str]] = {}
            cluster_run_ids: Dict[int, List[str]] = {}
            for d in source_data:
                cl = d.get("cluster_label", 0)
                if cl not in cluster_texts:
                    cluster_texts[cl] = []
                    cluster_run_ids[cl] = []
                cluster_texts[cl].append(d["text_analyzed"])
                cluster_run_ids[cl].append(d["run_id"])

            # LLM-summarize each cluster
            cluster_summaries = await self._summarize_clusters(cluster_texts, llm)

            # Build cluster_info artifact
            clusters = []
            for cl in sorted(cluster_summaries.keys()):
                clusters.append({
                    "cluster_id": cl,
                    "count": len(cluster_texts.get(cl, [])),
                    "summary": cluster_summaries[cl],
                    "run_ids": cluster_run_ids.get(cl, []),
                    "sample_texts": [t[:300] for t in cluster_texts.get(cl, [])[:3]],
                })

            artifact = {
                "name": f"{node_name} cluster info",
                "node_name": node_name,
                "data": {
                    "clusters": clusters,
                    "n_traces": len(source_data),
                    "n_clusters": len(clusters),
                    "uniformity_metrics": node_data.get("uniformity_metrics", {}),
                    "source_data": source_data,
                },
            }

            await state.artifacts().from_plugin(self.name).kind("cluster_info").save([artifact])
            self._log(f"Saved cluster_info for {node_name}: {len(clusters)} clusters")
            return artifact

        # Process all nodes in parallel — LLM cluster summarization calls overlap
        results = await asyncio.gather(
            *[_process_one_cluster(nd) for nd in node_data_list],
            return_exceptions=True,
        )

        artifacts_produced = sum(
            1 for r in results if r is not None and not isinstance(r, Exception)
        )

        for i, r in enumerate(results):
            if isinstance(r, Exception):
                node_name = node_data_list[i].get("node_name", "unknown")
                self._log(f"Error processing cluster info for {node_name}: {r}", level="error")

        return {
            "status": "needs_labeling",
            "message": (
                f"Saved cluster_info for {artifacts_produced} node(s). "
                "Use /disambiguate to label clusters via chat, or provide labels_csv."
            ),
            "artifacts_produced": artifacts_produced,
        }

    # ── Shared: Process a labeled node ───────────────────────────

    async def _process_labeled_node(
        self, state, node_name: str, source_data: List[Dict],
        node_data: Dict, df_labeled: pl.DataFrame, llm
    ) -> Optional[Dict]:
        """Validate, summarize, aggregate, and save a labeled node's traces."""
        if len(df_labeled) < 5:
            self._log(
                f"Only {len(df_labeled)} labeled traces for {node_name} (need >= 5), skipping.",
                level="warning",
            )
            return None

        label_counts = df_labeled.group_by("label").len().to_dicts()
        label_dist = {str(r["label"]): r["len"] for r in label_counts}

        if len(label_dist) < 2:
            self._log(f"Only one class for {node_name}, skipping.", level="warning")
            return None
        if min(label_dist.values()) < 2:
            self._log(f"Smallest class has < 2 traces for {node_name}, skipping.", level="warning")
            return None

        # LLM-summarize each trace entry
        self._log(f"Summarizing {len(df_labeled)} traces for {node_name}...")
        texts = df_labeled["text_analyzed"].to_list()
        summaries = await self._summarize_all(texts, llm)

        df_labeled = df_labeled.with_columns(pl.Series("summary_clean", summaries))

        # Aggregate by run_id
        df_agg = (
            df_labeled.group_by("run_id")
            .agg(
                pl.col("summary_clean")
                .cast(pl.Utf8)
                .str.concat(delimiter="\n-> ")
                .alias("full_story"),
                pl.col("label").first().alias("label"),
            )
        )

        if len(df_agg) < 5:
            self._log(f"Only {len(df_agg)} unique run_ids for {node_name}, skipping.", level="warning")
            return None

        aggregated_traces = [
            {
                "run_id": row["run_id"],
                "full_story": row["full_story"],
                "label": int(row["label"]),
            }
            for row in df_agg.iter_rows(named=True)
        ]

        artifact = {
            "name": f"{node_name} aggregated traces",
            "node_name": node_name,
            "data": {
                "aggregated_traces": aggregated_traces,
                "source_data": source_data,
                "uniformity_metrics": node_data.get("uniformity_metrics", {}),
                "n_traces": len(df_labeled),
                "n_unique_runs": len(df_agg),
                "label_distribution": label_dist,
            },
        }

        await state.artifacts().from_plugin(self.name).kind("node_traces").save([artifact])
        self._log(f"Saved node_traces for {node_name}: {len(df_agg)} runs, labels={label_dist}")
        return artifact

    # ── Interactive Cluster Labeling (CLI callback) ──────────────

    async def _label_via_interactive(
        self, df: pl.DataFrame, source_data: List[Dict], node_name: str, state, llm
    ) -> Optional[pl.DataFrame]:
        """Label traces interactively: LLM summarizes clusters, user picks which is success."""
        cluster_labels = set(d.get("cluster_label", 0) for d in source_data)
        if len(cluster_labels) < 2:
            self._log(f"Only {len(cluster_labels)} cluster(s) for {node_name} — cannot label.", level="warning")
            return None

        # Group trace texts by cluster
        cluster_texts: Dict[int, List[str]] = {}
        for d in source_data:
            cl = d.get("cluster_label", 0)
            if cl not in cluster_texts:
                cluster_texts[cl] = []
            cluster_texts[cl].append(d["text_analyzed"])

        # LLM-summarize each cluster
        cluster_summaries = await self._summarize_clusters(cluster_texts, llm)

        # Build prompt for user
        sorted_clusters = sorted(cluster_summaries.keys())
        prompt_lines = [
            f"Node: **{node_name}** — {len(source_data)} traces grouped into {len(sorted_clusters)} behavioral clusters.\n",
            "Which cluster represents SUCCESS (desired behavior)?\n",
        ]
        choices = []
        for cl in sorted_clusters:
            count = len(cluster_texts.get(cl, []))
            summary = cluster_summaries[cl]
            choice_text = f"Cluster {cl} ({count} traces): {summary}"
            choices.append(choice_text)

        prompt_text = "".join(prompt_lines)

        selected = await state.request_user_input(prompt_text, choices)
        if selected is None:
            self._log("User did not respond to cluster labeling.", level="warning")
            return None

        # Parse selected cluster number
        success_cluster = None
        for cl in sorted_clusters:
            if selected.startswith(f"Cluster {cl} "):
                success_cluster = cl
                break

        if success_cluster is None:
            self._log(f"Could not parse cluster from selection: {selected}", level="warning")
            return None

        self._log(f"User selected cluster {success_cluster} as SUCCESS for {node_name}.")

        label_map = {cl: (1 if cl == success_cluster else 0) for cl in sorted_clusters}
        labels = [label_map.get(d.get("cluster_label", 0), 0) for d in source_data]

        return df.with_columns(pl.Series("label", labels))

    async def _summarize_clusters(
        self, cluster_texts: Dict[int, List[str]], llm
    ) -> Dict[int, str]:
        """LLM-summarize each cluster's behavior from sample traces."""

        async def _summarize_one_cluster(cl: int, texts: List[str]) -> tuple:
            samples = texts[:5]
            samples_text = "\n---\n".join(s[:500] for s in samples)
            prompt = CLUSTER_SUMMARY_USER_TEMPLATE.format(
                n_samples=len(samples), samples_text=samples_text
            )
            try:
                response = await llm.call_llm(
                    user_prompt=prompt,
                    system_prompt=CLUSTER_SUMMARY_SYSTEM_PROMPT,
                    attributes={"max_tokens": 300, "temperature": 0},
                )
                return cl, response.content.strip()
            except Exception:
                return cl, f"({len(texts)} traces — summary unavailable)"

        results = await asyncio.gather(
            *[_summarize_one_cluster(cl, texts) for cl, texts in cluster_texts.items()]
        )
        return dict(results)

    # ── Data Loading ──────────────────────────────────────────────

    async def _load_node_data(self, state) -> List[Dict]:
        """Load node data from state (tasks after span_to_task) or from filesystem."""
        node_data = await self._load_from_state(state)
        if node_data:
            self._log(f"Loaded {len(node_data)} nodes from state (tasks)")
            return node_data

        if self.data_dir:
            node_data = self._load_from_filesystem()
            if node_data:
                self._log(f"Loaded {len(node_data)} nodes from filesystem ({self.data_dir})")
                return node_data

        return []

    async def _load_from_state(self, state) -> List[Dict]:
        """Build per-node data from tasks/spans in state (after span_to_task)."""
        try:
            tasks_result = await state.artifacts().kind("task").get()
            tasks = tasks_result.to_list() if tasks_result else []

            self._log(f"Loaded {len(tasks)} tasks from state")

            if not tasks or len(tasks) < 5:
                self._log(f"Not enough tasks ({len(tasks)}), need at least 5")
                return []

            node_groups: Dict[str, List[Dict]] = {}
            skipped_no_name = 0
            for task in tasks:
                node_name = self._extract_node_name_from_task(task)
                if not node_name:
                    skipped_no_name += 1
                    continue
                if node_name not in node_groups:
                    node_groups[node_name] = []
                node_groups[node_name].append(task)

            self._log(
                f"Grouped into {len(node_groups)} nodes "
                f"(skipped {skipped_no_name} tasks with no node name). "
                f"Nodes: {list(node_groups.keys())}"
            )

            if not node_groups:
                return []

            node_data_list = []
            for node_name, group_tasks in node_groups.items():
                source_data = []
                skipped_no_text = 0
                for t in group_tasks:
                    text = self._extract_output_text(t)
                    if not text:
                        skipped_no_text += 1
                        continue
                    source_data.append({
                        "run_id": str(t.get("trace_id", t.get("id", ""))),
                        "task_id": str(t.get("id", "")),
                        "text_analyzed": text,
                        "cluster_label": 0,
                    })

                self._log(
                    f"  Node '{node_name}': {len(source_data)} texts extracted, "
                    f"{skipped_no_text} skipped (no output text)"
                )

                if not source_data:
                    continue

                uniformity_metrics = self._compute_uniformity(source_data)

                node_data_list.append({
                    "node_name": node_name,
                    "source_data": source_data,
                    "uniformity_metrics": uniformity_metrics,
                })

            return node_data_list
        except Exception as e:
            self._log(f"Failed to load from state: {e}", level="error")
            import traceback
            traceback.print_exc()
            return []

    def _load_from_filesystem(self) -> List[Dict]:
        """Load pre-existing debug_data files from filesystem."""
        import glob

        pattern = os.path.join(self.data_dir, "debug_data_*-llm_call.json")
        files = sorted(glob.glob(pattern))
        files = [f for f in files if "LangGraph_workflow" not in os.path.basename(f)]

        if not files:
            return []

        node_data_list = []
        for filepath in files:
            base = os.path.basename(filepath)
            node_name = base.replace("debug_data_ALL_", "").replace("-llm_call.json", "")

            try:
                with open(filepath) as f:
                    data = json.load(f)

                source_data = data.get("source_data", [])
                if not source_data:
                    continue

                metrics = data.get("calculated_metrics", {})
                uniformity_metrics = {}
                if isinstance(metrics, list):
                    for m in metrics:
                        if "Uniformity" in m.get("element_id", ""):
                            uniformity_metrics["uniformity"] = m.get("value", 0)
                        if "BehavioralClusters" in m.get("element_id", ""):
                            uniformity_metrics["n_clusters"] = int(m.get("value", 0))
                elif isinstance(metrics, dict):
                    uniformity_metrics = metrics

                node_data_list.append({
                    "node_name": node_name,
                    "source_data": source_data,
                    "uniformity_metrics": uniformity_metrics,
                })
            except Exception as e:
                self._log(f"Failed to load {filepath}: {e}", level="warning")

        return node_data_list

    # ── Uniformity Computation ────────────────────────────────────

    def _compute_uniformity(self, source_data: List[Dict]) -> Dict:
        """Compute uniformity metrics for a group of traces via embedding + clustering."""
        try:
            from sentence_transformers import SentenceTransformer
            from sklearn.cluster import AgglomerativeClustering
            import numpy as np
        except ImportError:
            self._log(
                "Missing deps for uniformity. Install with: pip install agent-mentor[experiment]",
                level="warning",
            )
            return {}

        texts = [d["text_analyzed"] for d in source_data]
        if len(texts) < 2:
            return {"uniformity": 1.0, "n_clusters": 1}

        embedder = SentenceTransformer(self.embedding_model)
        embeddings = embedder.encode(texts)

        norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1, norms)
        normalized = embeddings / norms
        sim_matrix = normalized @ normalized.T
        avg_similarity = float(np.mean(sim_matrix[np.triu_indices_from(sim_matrix, k=1)]))

        dist_matrix = 1 - sim_matrix
        np.fill_diagonal(dist_matrix, 0)
        dist_matrix = np.clip(dist_matrix, 0, None)

        if len(texts) >= 2:
            try:
                clustering = AgglomerativeClustering(
                    n_clusters=None,
                    distance_threshold=self.distance_threshold,
                    metric="precomputed",
                    linkage="average",
                )
                labels = clustering.fit_predict(dist_matrix)
                n_clusters = len(set(labels))

                for i, label in enumerate(labels):
                    source_data[i]["cluster_label"] = int(label)
            except Exception:
                n_clusters = 1
        else:
            n_clusters = 1

        return {
            "uniformity": round(avg_similarity, 4),
            "n_clusters": n_clusters,
        }

    # ── Task Helpers ──────────────────────────────────────────────

    @staticmethod
    def _extract_node_name_from_task(task: Dict) -> Optional[str]:
        """Extract a node name from a task artifact.

        Handles both nested attributes dict and flattened 'attributes.key' format
        (the latter is used when tasks are loaded from the artifact store).
        """
        name = task.get("name", "")
        if not name:
            name = task.get("operation_name", "")

        # Check nested attributes dict
        attrs = task.get("attributes") or {}
        for key in ["agent_name", "node_name", "langgraph_node", "langgraph.node", "crewai.agent.role"]:
            if key in attrs and attrs[key]:
                return str(attrs[key])

        # Check flattened attributes (e.g., 'attributes.langgraph_node')
        for key in ["agent_name", "node_name", "langgraph_node", "langgraph.node", "crewai.agent.role"]:
            flat_key = f"attributes.{key}"
            if flat_key in task and task[flat_key]:
                return str(task[flat_key])

        if name and name not in ("LLMChain", "ChatOpenAI", ""):
            return str(name)

        return None

    @staticmethod
    def _extract_output_text(task: Dict) -> Optional[str]:
        """Extract output text from a task artifact.

        Handles multiple formats:
        - Top-level output/result/response fields
        - data as JSON string (artifact store format) or dict
        - LangChain message structure: data.output.outputs.messages[].kwargs.content
        - Flattened attributes (e.g., 'attributes.gen_ai.completion')
        """
        # Check top-level fields
        for key in ["output", "result", "response"]:
            val = task.get(key)
            if val and isinstance(val, str):
                return val

        # Parse data field (may be JSON string from artifact store)
        data = task.get("data")
        if isinstance(data, str):
            try:
                data = json.loads(data)
            except (json.JSONDecodeError, TypeError):
                data = None

        if isinstance(data, dict):
            for key in ["output", "result", "response"]:
                val = data.get(key)
                if not val:
                    continue

                # Parse nested JSON string (e.g., data["output"] is itself a JSON string)
                if isinstance(val, str):
                    try:
                        parsed = json.loads(val)
                    except (json.JSONDecodeError, TypeError):
                        return val  # Plain text output
                    val = parsed

                # Handle LangChain message structure:
                # {outputs: {messages: [{kwargs: {content: "..."}}]}}
                if isinstance(val, dict):
                    messages = val.get("outputs", {}).get("messages", [])
                    if messages:
                        # Get the last AI message with non-empty content
                        # Skip system/human messages and AI messages with empty content (tool calls)
                        for msg in reversed(messages):
                            msg_type = msg.get("kwargs", {}).get("type", "")
                            content = msg.get("kwargs", {}).get("content", "")
                            # Only return AI messages with actual text content
                            if msg_type == "ai" and content and content.strip():
                                return content

                    # Fallback: return as JSON
                    return json.dumps(val)

        # Check nested attributes dict
        attrs = task.get("attributes") or {}
        if isinstance(attrs, dict):
            for key in ["output", "gen_ai.completion", "traceloop.entity.output"]:
                val = attrs.get(key)
                if val:
                    if isinstance(val, str):
                        return val
                    return json.dumps(val)

        # Check flattened attributes (e.g., 'attributes.gen_ai.completion')
        for key in ["output", "gen_ai.completion", "traceloop.entity.output"]:
            flat_key = f"attributes.{key}"
            if flat_key in task and task[flat_key]:
                return str(task[flat_key])

        return None

    # ── Labels Loading ────────────────────────────────────────────

    def _load_labels_csv(self, csv_path: str) -> Optional[pl.DataFrame]:
        """Load labels CSV supporting Format A (run_id,label) and Format B (trace_log_filename)."""
        try:
            raw_df = pl.read_csv(csv_path)
        except Exception as e:
            self._log(f"Failed to read labels CSV: {e}", level="error")
            return None

        col_map = {c: c.strip().lower() for c in raw_df.columns}
        raw_df = raw_df.rename(col_map)

        if "trace_log_filename" in raw_df.columns and "result" in raw_df.columns:
            return self._load_labels_format_b(raw_df)

        id_col = None
        for c in ["run_id", "trace_id", "id", "trace"]:
            if c in raw_df.columns:
                id_col = c
                break

        label_col = None
        for c in ["label", "success", "result", "outcome", "status"]:
            if c in raw_df.columns:
                label_col = c
                break

        if id_col is None or label_col is None:
            self._log(f"CSV needs id + label columns. Found: {raw_df.columns}", level="error")
            return None

        return raw_df.select(
            pl.col(id_col).cast(pl.Utf8).alias("run_id"),
            pl.col(label_col).cast(pl.Int64).alias("label"),
        )

    def _load_labels_format_b(self, raw_df: pl.DataFrame) -> Optional[pl.DataFrame]:
        """Load Format B labels (trace_log_filename + result) by extracting trace IDs from logs."""
        if not self.logs_dir:
            self._log("CSV uses trace_log_filename format but logs_dir not configured.", level="error")
            return None

        rows = []
        for row in raw_df.iter_rows(named=True):
            result = str(row.get("result", "")).strip().lower()
            if result == "infra_fail":
                continue
            label = 1 if result == "success" else 0
            log_path = os.path.join(self.logs_dir, str(row["trace_log_filename"]).strip())
            if not os.path.exists(log_path):
                continue
            for tid in self._extract_trace_ids_from_log(log_path):
                rows.append({"run_id": tid, "label": label})

        if not rows:
            self._log("No trace_ids extracted from log files", level="error")
            return None

        df = pl.DataFrame(rows)
        df = df.group_by("run_id").agg(
            pl.col("label").mode().first().alias("label")
        )
        return df

    @staticmethod
    def _extract_trace_ids_from_log(log_path: str) -> set:
        """Extract OTEL trace_ids from a log file using regex."""
        try:
            with open(log_path) as f:
                content = f.read()
            return set(re.findall(r'"trace_id":\s*"(0x[0-9a-f]+)"', content))
        except Exception:
            return set()

    # ── LLM Summarization ─────────────────────────────────────────

    async def _summarize_all(self, texts: List[str], llm) -> List[str]:
        """LLM-summarize all trace entries with concurrency control."""
        sem = asyncio.Semaphore(self.max_concurrent_summarize)

        async def _summarize_one(text: str) -> str:
            async with sem:
                try:
                    safe_text = str(text)[:2000]
                    prompt = SUMMARIZE_USER_TEMPLATE.format(text=safe_text)
                    response = await llm.call_llm(
                        user_prompt=prompt,
                        system_prompt=SUMMARIZE_SYSTEM_PROMPT,
                        attributes={"max_tokens": 200, "temperature": 0},
                    )
                    return response.content.strip()
                except Exception:
                    return "action unclear"

        return await asyncio.gather(*[_summarize_one(t) for t in texts])
